### PR TITLE
fixing a 0-dim tensor to python warning to prevent a break come PyTorch 0.5. Pertinent to ExplicitFactorizationModel and ImplicitFactorizationModel.

### PR DESCRIPTION
**Pull request by nikisix**

### CODE REVIEW

**Comment by nikisix** [comment]
I'm on OSX and installed with pip. Which I attribute to the discrepancy.  Guess we'll see if this is a pip/conda issue come PyTorch 0.5

**Comment by nikisix** [comment]
I see, would you rather I close this for now then?

**Comment by maciejkula** [comment]
That depends! I don't know how much we actually need to change, and I don't know how keen you are on doing some of the work. If you have time, and are looking for an issue to work on, I'd be happy to collaborate with you on that. Otherwise, I'll get round to this myself in the next couple of weeks.

**Comment by nikisix** [comment]
After taking a quick peek for resizes, these guys may be the offenders

```
spotlight/factorization/implicit.py
276:                                                            .resize(batch_size, 1)
278:                                                            .resize(batch_size * n))

spotlight/sequence/representations.py
550:        user_representations = user_representations.resize(batch_size,
```

**Comment by maciejkula** [comment]
If you push the requirements changes to this PR we'll be able to see what needs fixing in the CI logs.

**Comment by nikisix** [comment]
Ok, looks like you ran the upgrade yesterday. I'll close this out then.

**Comment by maciejkula** [comment]
Yes, sorry --- I got some time over the weekend.

**Pull request closed without merging**
